<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kiberone.Core\Kiberone.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\shb-2026-2027.json" />
  </ItemGroup>
</Project>
